name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Test conversion functionality
        run: |
          if [ "$RUNNER_OS" != "Windows" ]; then
            node ConvertXmlToHtml.js --help
          else
            node ConvertXmlToHtml.js --help
          fi
        shell: bash

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run security audit
        run: npm audit --audit-level=high || echo "Audit terminé avec avertissements"
        continue-on-error: true

  build:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Validate package
        run: npm run validate || echo "Validation terminée"
        continue-on-error: true

      - name: Create release info
        run: |
          echo "✅ OptimXmlPreview v2.0 - Build réussi" > build-info.txt
          echo "📅 Date: $(date)" >> build-info.txt
          echo "🔗 Commit: ${{ github.sha }}" >> build-info.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: build-info.txt
